export const colors = {
  primary: '#FF4081',
  body: '#2A2A2A',
  constrastBody: '#F5F5F5',
  header1: '#0B644B',
  header2: '#527283',
  layer1: '#FFFFFF',
  layer2: '#F2F2F2',
  layer3: '#FAFAFA',
  panel: '#F8F8F8',
  warning: '#EBD147',
  danger: '#EB7E47',
  success: '#7EEB47',
  accent: '#EB4747',
  attention: '#FF4081',
  info: '#4799EB',
  seperator: '#cccccc',
  hideBody: 'hsl(0, 0%, 60%)',
  gray0: 'hsl(0, 0%, 0%)',
  gray10: 'hsl(0, 0%, 10%)',
  gray20: 'hsl(0, 0%, 20%)',
  gray30: 'hsl(0, 0%, 30%)',
  gray40: 'hsl(0, 0%, 40%)',
  gray50: 'hsl(0, 0%, 50%)',
  gray60: 'hsl(0, 0%, 60%)',
  gray70: 'hsl(0, 0%, 70%)',
  gray80: 'hsl(0, 0%, 80%)',
  gray90: 'hsl(0, 0%, 90%)',
  gray92: 'hsl(0, 0%, 92%)',
  gray94: 'hsl(0, 0%, 94%)',
  gray96: 'hsl(0, 0%, 96%)',
  gray98: 'hsl(0, 0%, 98%)',
  gray100: 'hsl(0, 0%, 100%)',
};

export const fonts = {
  headerXL: {
    //        fontFamily: "VarelaRound-Regular",
    fontWeight: '700',
    lineHeight: 41.6,
    fontSize: 32,
  },
  headerLG: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '600',
    lineHeight: 26,
    fontSize: 22,
  },
  headerMD: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '500',
    lineHeight: 24.7,
    fontSize: 20,
  },
  headerSM: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '400',
    lineHeight: 23.4,
    fontSize: 18,
  },
  headerXS: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '400',
    lineHeight: 23.06,
    fontSize: 16,
  },
  headerRG: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '400',
    lineHeight: 22.72,
    fontSize: 14,
  },
  headerXXSM: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '400',
    lineHeight: 20.72,
    fontSize: 12,
  },
  body: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '400',
    lineHeight: 22.72,
    fontSize: 14,
  },
  caption: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '400',
    letterSpacing: -0.5,
    lineHeight: 14.4,
    fontSize: 10,
  },
  button: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '400',
    lineHeight: 23.4,
    fontSize: 18,
  },
  overline: {
    // fontFamily: 'VarelaRound-Regular',
    fontWeight: '400',
    textTransform: 'uppercase',
    letterSpacing: 2,
    fontSize: 12,
  },
};

const theme = {
  key: 'light',
  fonts,
  colors,
};

export default theme;
